# Generated by Django 6.0.2 on 2026-07-22 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_ends_at',
            field=models.DateTimeField(blank=True, help_text='Если не указано — скидка бессрочна (пока не выключена).', null=True, verbose_name='Конец акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='От 0 до 100. 0 — скидки нет.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_starts_at',
            field=models.DateTimeField(blank=True, help_text='Если не указано — скидка действует сразу.', null=True, verbose_name='Начало акции'),
        ),
    ]